/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.14 public/models/eighty.gltf 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useCustomization } from "./contexts/Customization";

const Eighty = (props) => {
  const { nodes, materials } = useGLTF("/models/eighty.gltf");
  const { baseColor, insideBaseColor, keyColor, keyOtherColor, keyThirdColor } =
    useCustomization();

  return (
    <group {...props} dispose={null}>
      <group position={[0.048, 0.238, 0.104]} scale={[3.508, 1.361, 1.361]}>
        <mesh geometry={nodes.Plane154.geometry}>
          <meshStandardMaterial color={insideBaseColor.color} />
        </mesh>
        <mesh geometry={nodes.Plane154_1.geometry}>
          <meshStandardMaterial color={baseColor.color} />
        </mesh>
        <mesh geometry={nodes.Plane154_2.geometry}>
          <meshStandardMaterial color={baseColor.color} />
        </mesh>
      </group>
      <group position={[-4.583, 0.405, 0.088]} scale={0.215}>
        <mesh geometry={nodes.Plane308.geometry}>
          <meshStandardMaterial color={keyColor.color} />
        </mesh>
        <mesh geometry={nodes.Plane308_1.geometry}>
          <meshStandardMaterial color={keyThirdColor.color} />
        </mesh>
        <mesh geometry={nodes.Plane308_2.geometry}>
          <meshStandardMaterial color={keyOtherColor.color} />
        </mesh>
      </group>
      <mesh
        geometry={nodes.LIGHT_A.geometry}
        material={materials.Light}
        position={[3.389, 0.442, 0.067]}
        rotation={[0, Math.PI / 2, 0]}
        scale={0.037}
      />
      <mesh
        geometry={nodes.Text060.geometry}
        material={materials.text}
        position={[2.691, 0.874, -0.86]}
        scale={0.075}
      />
    </group>
  );
};

useGLTF.preload("/eighty.gltf");
export default Eighty;
