/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.14 public/models/hundred.gltf 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useCustomization } from "./contexts/Customization";

const Hundred = (props) => {
  const { nodes, materials } = useGLTF("/models/hundred.gltf");
  const { baseColor, insideBaseColor, keyColor, keyOtherColor, keyThirdColor } =
    useCustomization();

  return (
    <group {...props} dispose={null}>
      <group position={[0.048, 0.238, 0.104]} scale={[3.508, 1.361, 1.361]}>
        <mesh geometry={nodes.Plane154.geometry}>
          <meshStandardMaterial color={insideBaseColor.color} />
        </mesh>
        <mesh geometry={nodes.Plane154_1.geometry}>
          <meshStandardMaterial color={baseColor.color} />
        </mesh>
        <mesh geometry={nodes.Plane154_2.geometry}>
          <meshStandardMaterial color={baseColor.color} />
        </mesh>
      </group>
      <group position={[3.226, 0.55, -1.256]} scale={0.215}>
        <mesh geometry={nodes.Plane442.geometry}>
          <meshStandardMaterial color={keyColor.color} />
        </mesh>
        <mesh geometry={nodes.Plane442_1.geometry}>
          <meshStandardMaterial color={keyThirdColor.color} />
        </mesh>
        <mesh geometry={nodes.Plane442_2.geometry}>
          <meshStandardMaterial color={keyOtherColor.color} />
        </mesh>
      </group>
      <mesh
        geometry={nodes.lights.geometry}
        material={materials.Light}
        position={[6.409, 0.594, -1.18]}
        rotation={[-3.077, 0, 3.12]}
        scale={0.037}
      />
      <mesh
        geometry={nodes.Text016.geometry}
        material={materials.text}
        position={[6.604, 0.704, 0.526]}
        rotation={[0.073, 0, 0]}
        scale={0.09}
      />
      <mesh
        geometry={nodes.Text_lightS.geometry}
        material={materials.Light}
        position={[5.422, 0.66, -1.303]}
        scale={0.067}
      />
    </group>
  );
};

useGLTF.preload("/hundred.gltf");
export default Hundred;
