/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.14 public/models/numpad.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF, useTexture } from '@react-three/drei'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'
import { useLoader } from '@react-three/fiber'

const Numpad = (props) => {
  const { nodes, materials } = useLoader(GLTFLoader, "/models/numpad.gltf");

  const plasticTextureProps = useTexture({
    map: "/textures/Plastic_001_COLOR.jpg",
    roughnessMap: "/textures/Plastic_001_ROUGHNESS.jpg",
  });

  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.014, 0]} scale={[1.044, 1, 1.503]}>
        <mesh geometry={nodes.Plane023.geometry} material={materials.Base} />
        <mesh geometry={nodes.Plane023_1.geometry} material={materials.Base2} />
      </group>
      <mesh geometry={nodes.Keys1.geometry} material={materials.Keys1} position={[-0.684, 0.342, -0.633]} scale={0.215} />
      <mesh geometry={nodes.Keys2.geometry} material={materials.Keys2} position={[-0.684, 0.342, -0.633]} scale={0.215} />
      <mesh geometry={nodes.Text.geometry} material={materials.text} position={[0.635, 0.706, -1.154]} scale={0.118} />
    </group>
  )
}

useGLTF.preload('/numpad.gltf')

export default Numpad